### PR TITLE
Add :i18n/language datomic attribute

### PR DESCRIPTION
**Pull request by cap10morgan**
Adding this will allow us to set all existing instruction entities to `:en` before we deploy the version of election-authority-works that expects languages on its instructions. It doesn't harm the current code to have the extra attribute (it just ignores it).

This is part of the i18n deployment plan we discussed yesterday. It seems to have worked out the way we'd hoped.

Note that the changes to import are small indentation fixes.

### CODE REVIEW

**Comment by tank157** [comment]
Remind me again, there was a reason to do this separately and earlier than we'd be doing it again in the other PR which adds full support for the language? Should we pull the migration from the other PR? https://github.com/democracyworks/election-authority-works/pull/29

**Comment by cap10morgan** [comment]
The reason is that by doing this first, the data will already be compatible with the new code once it's deployed rather than having a window where it's not or needing to accommodate both in the new code.

I copied the migration straight from that branch. Does something look inconsistent?

**Comment by cap10morgan** [comment]
Oh you mean remove it from the other branch? Nah, should be harmless to leave it there and it makes that branch hang together in and of itself.

**Comment by tank157** [comment]
Ahhh, I see, they have the same name, so presumably they'll just merge seamlessly over each other. Ok, LGTM

**Pull request merged**
