### PR TITLE
Create and read queues

### PR DESCRIPTION
**Pull request by ericnormand**
Create and read queues for the election-authority-works CRUD API.

Includes tests.

## NOTES

After a discussion with the team, we chose not to have hierarchical ocd ids. We will be searching for the hierarchy so an exact match is precise.

The pivotal card does mention *maybe* doing update and delete but indicated they were optional.

### Create an election authority:

send to `election-authority-works.create`

```
{:office-name "My authority"
           :official-title "My title"
           :types #{:registration :election}
           :physical-address {:street "1010 Main St."
                              :street-2 "Suite 2000002"
                              :city "Los Angeles"
                              :state "WY"
                              :zip "77877"
                              :routing-code "43432"}
           :mailing-address {:street "1010 Main St."
                             :street-2 "Suite 2000002"
                             :city "Los Angeles"
                             :state "WY"
                             :zip "77877"
                             :routing-code "43432"}
           :homepage-url "http://www.authority.com/"
           :phone "443-232-3232"
           :email "dude@authority.com"
           ;; [ocd-id description]
           :ocd-division ["ocd-division/country:us" "USA"]}
```

### Read an election authority

send to `election-authority-works.read`

```
{:id #uuid "...."}
```

[Pivotal Card](https://www.pivotaltracker.com/story/show/95884058)

### CODE REVIEW

**Comment by ericnormand** [comment]
We ran tests with `lein test` with all passes.

**Comment by ericnormand** [comment]
Assigning to @dcohen, who rocks!

**Comment by ericnormand** [comment]
Tested queues manually at the RabbitMQ console.

**Comment by dcohen** [comment]
LGTM!

**Pull request merged**
