### PR TITLE
New data model

### PR DESCRIPTION
**Pull request by ericnormand**
Rework the data model to reflect how we are using it.

Election authorities are no longer at the center. Now, ocd-divisions are the main entity. voter-reg/voting methods belong to the division. Authorities are sub-components of their divisions.

Upserting is based only on the ocd-id, so all authorities will be replaced to what's in the passed-in message.

I think this better reflects how an admin screen might actually be built. We would want to show a screen for modifying the authorities for a given ocd division, not the other way around. Likewise, I think the questions we ask (for instance, are there any race instructions for registering in the state of Michigan?) are not about authorities but about the particulars of that division.

I think this simplifies a lot of the code, including the tests, which were complicated by the more complex upsert rules based on ocd-id and type.

I'm still working on the import/export using this model.

### CODE REVIEW

**Comment by danielglauser** [comment]
@ericnormand I thought a bit about this over the weekend. Is the entity really a municipality and the `ocd-id` is the unique identifier for it? Would love to hear what @cap10morgan and @tank157 think about this too.

**Comment by ericnormand** [comment]
@danielglauser Yeah, I think we were thinking about it backwards. We ask questions like "What forms can I use to register in Michigan?" or "What URL can I use to register online in New York?". We also want the authority information, but it's also a question like "What is the physical address of the election authority for Pam County, Utah?" Notice that what we know is the place. So I've just made that the root of the entity.

**Comment by cap10morgan** [comment]
It's possible that we've been thinking about it backwards, but it's also possible that we designed it this way to accommodate specific needs. I'll need to circle back with Katy and Monica to discuss this part of the data model before we merge this.

**Comment by ericnormand** [comment]
Yep, understood. If you'd like to talk about it with voice, @cap10morgan , let me know. You can see a full example of what the data model looks like in the division-test namespace.

**Comment by kep** [comment]
@cap10morgan The Ocho flagged this for me this morning, so I've taken a preliminary look around and feel reasonably good about it, and I'd love to dive into it with you in detail to make sure I haven't overlooked any strange corners.

**Comment by cap10morgan** [comment]
I'm inclined to revisit the data model question in here after we get turbovote.org running on the rewrite early in 2016. Does that seem OK to everyone, or is there a pressing need to figure this out sooner than that?

**Comment by cap10morgan** [comment]
Actually, looking at the [data model docs](https://torchpad.com/workspace/wikis/democracyworks/pages/data+models/elections#Election-authority-data-model) it appears that we were already specify a cardinality-one ref of the authority to the division anyway. So this is probably fine from a data model perspective.

But we would need to modify the message schemas and version those, right?

**Comment by ddellacosta** [comment]
@cap10morgan Just noticed this hanging out in here. Can we close this?

**Comment by ericnormand** [comment]
Fine by me ;)

**Comment by cap10morgan** [comment]
It sounds like this is conceptually still an improvement, but we would probably have to start the changes over again after so much time. Closing this for now.

**Pull request closed without merging**
