### PR TITLE
Remove office name

### PR DESCRIPTION
**Pull request by danielglauser**
Removes `:office-name` from the codebase and replaces it with `:official-title` to get some better coverage in the tests. Fixes a bug importing the latest Election Authorities spreadsheet.

[Card here](https://www.pivotaltracker.com/story/show/139840367).

### CODE REVIEW

**Comment by cap10morgan** [comment]
Why are we removing this? These 2 fields each have different purposes. The `:office-name` field is supposed to be for things like "Colorado Secretary of State" or "Jefferson County Elections", that is, the name of the office that runs elections at that level.

The `:official-title` field is intended to hold the title of the person that people should contact at that office. So things like "Election Clerk".

Both of these things often appear in addresses to send forms too and instructions for how to interact with a given election authority.

This PR and the card kind of imply that these fields are interchangeable (they are not) or that we meant one when we used the other (in which case that problem should be fixed elsewhere). If this is a problem in the authorities spreadsheet, maybe that should be fixed instead of changing this data model?

**Comment by cap10morgan** [comment]
In fact, it looks like the problem is that someone renamed the `office-name` column in the States tab of the authorities sheet to `mi`. So that seems like what we should fix.

**Comment by tank157** [comment]
Ok, yeah, let's get the spreadsheet header row fixed up and FREEZE it. And let's do that for all the import spreadsheets. This is like the third or fourth time errant edits in the header row has messed things up, and Google Docs is the Home of Errant Edits.

**Comment by cap10morgan** [comment]
OK, column fixed and I set a protected range on both sheets' column rows that shows a warning when you try to change them. You have to click OK on that before the change will go in.

Do we still want things from this PR or should we close it?

**Comment by danielglauser** [comment]
Thanks for clarifying @cap10morgan that wasn't clear to me. Closing this PR.

**Pull request closed without merging**
